# Generated by Django 2.0.5 on 2019-03-16 03:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='n/a', max_length=100)),
                ('category', models.CharField(choices=[('anime', 'anime'), ('manga', 'manga'), ('other', 'other')], default='n/a', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.IntegerField(null=True)),
                ('author', models.CharField(default='n/a', max_length=64)),
                ('verses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), null=True, size=5)),
                ('romanized_author', models.CharField(default='n/a', max_length=64)),
                ('romanized_verses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), null=True, size=5)),
            ],
            options={
                'ordering': ['numeral'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='n/a', max_length=100)),
                ('url', models.URLField(default='n/a')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('vn', 'Vietnamese')], default='en', max_length=16)),
                ('default', models.BooleanField(default=False)),
                ('translator', models.CharField(default='n/a', max_length=64)),
                ('translated_author', models.CharField(default='n/a', max_length=64)),
                ('translated_verses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), size=5)),
                ('poem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='api.Poem')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='api.Source')),
            ],
        ),
        migrations.AddField(
            model_name='poem',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poems', to='api.Source'),
        ),
        migrations.AddField(
            model_name='media',
            name='poem',
            field=models.ManyToManyField(null=True, related_name='media', to='api.Poem'),
        ),
    ]
