# Generated by Django 2.0.5 on 2019-03-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='poem',
            field=models.ManyToManyField(related_name='media', to='api.Poem'),
        ),
    ]
