# Generated by Django 2.0.5 on 2018-06-06 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=256)),
                ('line_2', models.CharField(max_length=256)),
                ('line_3', models.CharField(max_length=256)),
                ('line_4', models.CharField(max_length=256)),
                ('line_5', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Jap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=256)),
                ('line_2', models.CharField(max_length=256)),
                ('line_3', models.CharField(max_length=256)),
                ('line_4', models.CharField(max_length=256)),
                ('line_5', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.IntegerField()),
                ('jap_author', models.CharField(max_length=256)),
                ('rom_author', models.CharField(max_length=256)),
                ('eng_author', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Rom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=256)),
                ('line_2', models.CharField(max_length=256)),
                ('line_3', models.CharField(max_length=256)),
                ('line_4', models.CharField(max_length=256)),
                ('line_5', models.CharField(max_length=256)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.Poem')),
            ],
        ),
        migrations.AddField(
            model_name='jap',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.Poem'),
        ),
        migrations.AddField(
            model_name='eng',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.Poem'),
        ),
    ]
