# Generated by Django 2.0.5 on 2018-06-06 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eng',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jap',
            name='id',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='eng_author',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='jap_author',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='rom_author',
        ),
        migrations.RemoveField(
            model_name='rom',
            name='id',
        ),
        migrations.AddField(
            model_name='eng',
            name='author',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jap',
            name='author',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rom',
            name='author',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eng',
            name='poem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='poems.Poem'),
        ),
        migrations.AlterField(
            model_name='jap',
            name='poem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='poems.Poem'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='numeral',
            field=models.IntegerField(default=101),
        ),
        migrations.AlterField(
            model_name='rom',
            name='poem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='poems.Poem'),
        ),
    ]
