# Generated by Django 2.0.5 on 2018-06-06 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_auto_20180606_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eng',
            name='poem',
        ),
        migrations.RemoveField(
            model_name='jap',
            name='poem',
        ),
        migrations.RemoveField(
            model_name='rom',
            name='poem',
        ),
        migrations.DeleteModel(
            name='Eng',
        ),
        migrations.DeleteModel(
            name='Jap',
        ),
        migrations.DeleteModel(
            name='Rom',
        ),
    ]
