# Generated by Django 2.0.5 on 2018-06-07 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0004_jap'),
    ]

    operations = [
        migrations.AddField(
            model_name='jap',
            name='poem',
            field=models.OneToOneField(default=101, on_delete=django.db.models.deletion.CASCADE, to='poems.Poem'),
            preserve_default=False,
        ),
    ]
