# Generated by Django 2.0.5 on 2018-06-07 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0005_jap_poem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jap',
            name='poem',
            field=models.OneToOneField(default=101, on_delete=django.db.models.deletion.CASCADE, to='poems.Poem'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='numeral',
            field=models.IntegerField(),
        ),
    ]
