# Generated by Django 2.0.5 on 2018-06-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0006_auto_20180607_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='jap',
            name='line_1',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='jap',
            name='line_2',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='jap',
            name='line_3',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='jap',
            name='line_4',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='jap',
            name='line_5',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='jap',
            name='author',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
