# Generated by Django 2.0.5 on 2018-06-07 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0007_auto_20180607_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Unknown', max_length=100)),
                ('line_1', models.CharField(default='None', max_length=100)),
                ('line_2', models.CharField(default='None', max_length=100)),
                ('line_3', models.CharField(default='None', max_length=100)),
                ('line_4', models.CharField(default='None', max_length=100)),
                ('line_5', models.CharField(default='None', max_length=100)),
                ('poem', models.OneToOneField(default=101, on_delete=django.db.models.deletion.CASCADE, to='poems.Poem')),
            ],
        ),
        migrations.CreateModel(
            name='Rom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Unknown', max_length=100)),
                ('line_1', models.CharField(default='None', max_length=100)),
                ('line_2', models.CharField(default='None', max_length=100)),
                ('line_3', models.CharField(default='None', max_length=100)),
                ('line_4', models.CharField(default='None', max_length=100)),
                ('line_5', models.CharField(default='None', max_length=100)),
                ('poem', models.OneToOneField(default=101, on_delete=django.db.models.deletion.CASCADE, to='poems.Poem')),
            ],
        ),
        migrations.AlterField(
            model_name='jap',
            name='author',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
