# Generated by Django 2.0.5 on 2018-06-07 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0008_auto_20180607_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eng',
            name='poem',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='poems.Poem'),
        ),
        migrations.AlterField(
            model_name='jap',
            name='poem',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='poems.Poem'),
        ),
        migrations.AlterField(
            model_name='rom',
            name='poem',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='poems.Poem'),
        ),
    ]
