# Generated by Django 2.0.5 on 2018-06-07 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0009_auto_20180607_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eng',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jap',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rom',
            name='id',
        ),
        migrations.AlterField(
            model_name='eng',
            name='poem',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='poems.Poem'),
        ),
        migrations.AlterField(
            model_name='jap',
            name='poem',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='poems.Poem'),
        ),
        migrations.AlterField(
            model_name='rom',
            name='poem',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='poems.Poem'),
        ),
    ]
