"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/
"""

from decouple import config 
import inspect
import pkgutil

"""
Modular settings 
https://github.com/samiconductor/modularsettings/blob/master/modularsettings/settings/__init__.py
https://docs.python.org/3.4/library/inspect.html
https://docs.python.org/3/library/pkgutil.html
https://stackoverflow.com/a/28490054
"""

for _, module_name, _ in pkgutil.walk_packages(__path__):
	module = __import__(module_name, globals(), locals(), [], level=1)

	for var, val in inspect.getmembers(module):
		if var.isupper():
			locals().update({var: val})
