# Assets 
# https://docs.djangoproject.com/en/2.0/howto/static-files/

import os
from .paths import BASE_DIR, REACT_APP_DIR

# Absolute path to the location of user-uploaded files.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# URL prefix for media files served from MEDIA_ROOT.
# Example: "http://localhost:8000/media/"
MEDIA_URL = '/media/'

# List of finder classes that know how to find static 
# files in various locations.
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

# Absolute path to the location of static files collected 
# by collectstatic. WhiteNoise requires that static files 
# are collected to "staticfiles". 
# Don't put anything in this directory yourself. Store your 
# static files in individual apps' "static/" subdirectories 
# or in STATICFILES_DIRS. 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# URL prefix for static files served from STATIC_ROOT.
# Example: "http://localhost:8000/static/"
STATIC_URL = '/static/'

# Extra locations (absolute paths) of static files for collectstatic.
# Example: "/home/html/static" or "C:/www/django/static"
STATICFILES_DIRS = [
    os.path.join(REACT_APP_DIR, 'build', 'static'),
]

# React integration using django-webpack-loader 
# https://github.com/owais/django-webpack-loader#configuration

# This configuration requires that code-splitting is disabled in CRA2.
# https://github.com/facebook/create-react-app/issues/5306
WEBPACK_LOADER = {
    'DEFAULT': {
    	'CACHE': not DEV_ENV,
    	# Relative path to the dir of webpack bundles (relative to 
    	# static dirs defined in STATICFILES_DIRS);
        'BUNDLE_DIR_NAME': '',
        # Absolute path to the file generated by webpack-bundle-tracker js plugin
        'STATS_FILE': os.path.join(REACT_APP_DIR, 'webpack-stats-production.json'),
    }
}

 