# Generated by Django 2.0.5 on 2018-08-27 17:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('preferred_translator', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('jap', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='No verse', max_length=200), blank=True, null=True, size=6)),
                ('rom', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='No verse', max_length=200), blank=True, null=True, size=6)),
            ],
            options={
                'db_table': 'poems',
                'ordering': ('numeral',),
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='No verse', max_length=200), blank=True, null=True, size=6)),
                ('translator', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='karuta_api.Poem')),
            ],
            options={
                'db_table': 'translations',
            },
        ),
    ]
