# Generated by Django 2.0.5 on 2018-07-17 15:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karuta_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='eng',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='No verse', max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='poem',
            name='jap',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='No verse', max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='poem',
            name='rom',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='No verse', max_length=200), blank=True, null=True, size=None),
        ),
    ]
