# Generated by Django 2.0.5 on 2018-08-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karuta_api', '0003_auto_20180827_1810'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='translation',
            index_together={('eng', 'translator')},
        ),
    ]
