# Generated by Django 2.0.5 on 2018-08-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karuta_api', '0004_auto_20180827_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='translator',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('eng', 'poem', 'translator')},
        ),
    ]
