# Generated by Django 2.0.5 on 2018-06-09 23:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jap', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('rom', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('eng', models.CharField(blank=True, default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.IntegerField(default=-1, unique=True)),
                ('jap', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='None', max_length=200), blank=True, null=True, size=None)),
                ('rom', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='None', max_length=200), blank=True, null=True, size=None)),
                ('eng', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='None', max_length=200), blank=True, null=True, size=None)),
                ('author', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='karuta.Author')),
            ],
        ),
    ]
