# Generated by Django 2.0.5 on 2018-06-10 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karuta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karuta.Author'),
        ),
    ]
