# Generated by Django 2.0.5 on 2018-06-10 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karuta', '0002_auto_20180609_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='poem',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='karuta.Poem'),
        ),
    ]
