# Generated by Django 2.0.5 on 2018-06-10 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karuta', '0003_auto_20180609_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karuta.Poem'),
        ),
    ]
