# Generated by Django 2.0.5 on 2018-06-10 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karuta', '0004_auto_20180609_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='poem',
        ),
        migrations.AddField(
            model_name='poem',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='poem', to='karuta.Author'),
        ),
    ]
