# Generated by Django 2.0.5 on 2018-06-10 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karuta', '0005_auto_20180609_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poem', to='karuta.Author'),
        ),
    ]
