# Generated by Django 2.0.5 on 2018-06-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karuta', '0006_auto_20180609_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poem',
            options={'ordering': ('numeral',)},
        ),
        migrations.AlterField(
            model_name='poem',
            name='numeral',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
